issuer: 'PayPal'
keywords:
  - 'PayPal'
fields:
  invoice_number: 'payment/([A-Z0-9]+)'
  date: '(\d{1,2} \w+ \d{4})'
  amount: '-\$?([0-9,.]+)'
  currency_code: '(USD)'
options:
  date_formats:
    - '%d-%m-%Y'
    - '%d/%m/%Y'
    - '%Y-%m-%d'
  remove_whitespace: true
