issuer: 'ACTION'
keywords:
  - 'ACTION'
  - 'Wagnerplein'
  - 'ARTIKELEN'
fields:
  invoice_number: '1348102-10743227'
  date: '12-08-2024'
  amount: '3.27'
  currency_code: 'EUR'
options:
  date_formats:
    - '%d-%m-%Y'
    - '%d/%m/%Y'
    - '%Y-%m-%d'
  remove_whitespace: true
